config/routes.rb
HunkyDory::Engine.routes.draw do
  root to: 'changes#index'

  resources :changes
end

app/models/hunky_dory/application_record.rb
module HunkyDory
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/hunky_dory/change.rb
module HunkyDory
  class Change < ApplicationRecord
    with_options presence: true do
      validates :summary, length: { maximum: 255 }
      validates :after_description, length: { maximum: 10_000 }
    end

    validates :before_description, length: { maximum: 10_000 }
  end
end

app/controllers/hunky_dory/application_controller.rb
module HunkyDory
  class ApplicationController < Hunky::ApplicationController
    protect_from_forgery with: :exception

    def flash_errors(model_with_errors)
      messages = model_with_errors.errors.map do |attribute, message|
        "#{attribute.capitalize} #{message}"
      end
      flash[:danger] = messages.join(', ')
    end
  end
end

app/controllers/hunky_dory/changes_controller.rb
require_dependency 'hunky_dory/application_controller'

module HunkyDory
  class ChangesController < ApplicationController
    before_action :set_change, only: %i[show edit update destroy]

    def index
      @changes = Change.all.order(created_at: :desc)
    end

    def show; end

    def new
      @change = Change.new
    end

    def edit; end

    def create
      @change = Change.new(change_params)

      if @change.save
        flash[:success] = 'Change was successfully created.'
        redirect_to @change
      else
        flash_errors @change
        render :new
      end
    end

    def update
      if @change.update(change_params)
        flash[:success] = 'Change was successfully updated.'
        redirect_to @change
      else
        flash_errors @change
        render :edit
      end
    end

    def destroy
      @change.destroy
      flash[:success] = 'Change was successfully destroyed.'
      redirect_to changes_url
    end

    private

    def set_change
      @change = Change.find(params[:id])
    end

    def change_params
      params.require(:change)
            .permit(:summary, :before_description, :after_description)
    end
  end
end

app/helpers/hunky_dory/application_helper.rb
module HunkyDory
  module ApplicationHelper
    def render_markdown(text)
      options = {
        filter_html: true,
        link_attributes: { target: "_blank" }
      }

      extensions = {
        strikethrough: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      markdown.render(text).html_safe
    end
  end
end

app/views/hunky_dory/changes/_form.html.erb
<%= form_with(model: change, local: true) do |form| %>
  <%= form.label :summary %>
  <%= form.text_field :summary, id: :change_summary, class: 'u-full-width' %>

  <div class='row'>
    <div class="six columns">
      <%= form.label :before_description, 'How it used to be' %>
      <%= form.text_area :before_description,
        id: :change_before_description,
        class: 'u-full-width',
        rows: 10 %>
    </div>
    <div class="six columns">
      <%= form.label :after_description, "What's new" %>
      <%= form.text_area :after_description,
        id: :change_after_description,
        class: 'u-full-width',
        rows: 10 %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'button' %>
  </div>
<% end %>

app/views/hunky_dory/changes/edit.html.erb
<h1>Editing Change</h1>

<%= render 'form', change: @change %>
<div class='twelve columns'>
  <a href='http://commonmark.org/help/' target='_blank'>How do I use Markdown?</a>
</div>

<%= link_to 'Show', @change %> |
<%= link_to 'Back', root_path %>

app/views/hunky_dory/changes/index.html.erb
<h1>Changes</h1>
<hr id='page-break' />

<div class='row'>
  <div class='twelve columns' style='text-align: center;'>
    <%= link_to 'Add a Change', new_change_path, class: 'button', style: 'margin-top: 6px' %>
  </div>

  <div class='twelve columns'>
    <% if @changes.any? %>
      <table class='u-full-width changelog'>
        <thead>
          <tr>
            <th>Summary</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @changes.each do |change| %>
            <tr>
              <td><%= link_to change.summary, change %></td>
              <td><%= link_to 'Edit', edit_change_path(change), class: 'button button-primary' %></td>
              <td>
                <%= button_to 'Delete', change_path(change),
                    method: :delete, data: { confirm: 'Are you sure?' },
                    class: 'button button-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<%= paginate @changes %>

app/views/hunky_dory/changes/new.html.erb
<h1>New Change</h1>

<%= render 'form', change: @change %>

<%= link_to 'Back', root_path %>

app/views/hunky_dory/changes/show.html.erb
<h5>
  <%= @change.summary %>
</h5>
<hr id='page-break' />

<p>
  <% if @change.before_description.present? %>
    <strong>Before:</strong>
    <div class='rendered-markdown'>
      <%= render_markdown(@change.before_description) %>
    </div>
  <% end %>
</p>

<p>
  <strong>After:</strong>
  <div class='rendered-markdown'>
    <%= render_markdown(@change.after_description) %>
  </div>
</p>

<%= link_to 'Edit', edit_change_path(@change) %> |
<%= link_to 'Back', root_path %>

app/views/layouts/hunky_dory/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hunky dory</title>
  <%= stylesheet_link_tag    "hunky_dory/application", media: "all" %>
  <%= javascript_include_tag "hunky_dory/application" %>
  <%= csrf_meta_tags %>
</head>
<body id='hunky_dory'>
  <div class='container'>
    <br />

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type.to_s %>">
        <% if message.is_a? Array %>
          <ul>
            <% message.each do |m| %>
              <li><%= m %></li>
            <% end %>
          </ul>
        <% else %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <% flash.clear %>

    <%= yield %>
  </div>

</body>
</html>